<a href="https://colab.research.google.com/github/riyaagustine/didactic-goggles/blob/main/Handling_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [13]:
df = pd.read_csv('True.csv')

In [6]:
df.head(10)

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017"
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017"
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017"

In [7]:
df.tail(2)

,title,text,subject,date
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [8]:
df.isnull()

       title   text  subject   date
0      False  False    False  False
1      False  False    False  False
2      False  False    False  False
3      False  False    False  False
4      False  False    False  False
...      ...    ...      ...    ...
21412  False  False    False  False
21413  False  False    False  False
21414  False  False    False  False
21415  False  False    False  False
21416  False  False    False  False

[21417 rows x 4 columns]

In [10]:
df.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [15]:
df =pd.read_csv('/test.csv')

In [16]:
df.isnull()

   Name     Age  Experience  Salary
0  False  False       False   False
1  False  False       False   False
2  False  False       False   False
3  False  False        True   False
4   True  False       False    True
5   True  False        True    True

In [17]:
df.isnull().sum()

Name          2
Age           0
Experience    2
Salary        2
dtype: int64

In [18]:
df

    Name   Age  Experience    Salary
0   Riya    33        20.0  100000.0
1    Manu   37        17.0   90000.0
2  Melvin    1         2.0   10000.0
3   Susan   23         NaN   60000.0
4     NaN   45        23.0       NaN
5     NaN   35         NaN       NaN

In [19]:
df.describe()

             Age  Experience         Salary
count   6.000000    4.000000       4.000000
mean   29.000000   15.500000   65000.000000
std    15.440207    9.327379   40414.518843
min     1.000000    2.000000   10000.000000
25%    25.500000   13.250000   47500.000000
50%    34.000000   18.500000   75000.000000
75%    36.500000   20.750000   92500.000000
max    45.000000   23.000000  100000.000000

In [42]:
df.dropna(thresh=2, subset =['Experience', 'Salary'])

    Name   Age  Experience    Salary
0   Riya    33        20.0  100000.0
1    Manu   37        17.0   90000.0
2  Melvin    1         2.0   10000.0

In [40]:
# This will correctly keep rows 0, 1, 2, and 3 (where Salary has data)
df.dropna(subset=['Salary'])

    Name   Age  Experience    Salary
0   Riya    33        20.0  100000.0
1    Manu   37        17.0   90000.0
2  Melvin    1         2.0   10000.0
3   Susan   23         NaN   60000.0

Encoding Methods